name: Initialize Monorepo
description: Initialize nx monorepo for CI workflows

runs:
  using: 'composite'
  steps:
    - name: Use PNPM 9.x
      uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
    - name: Install Node.js Dependencies
      shell: bash
      run: pnpm i --frozen-lockfile --prefer-offline
    - name: Set git identity
      shell: bash
      run: |-
        git config user.name "release"
        git config user.email "release@github.com"
    - uses: nrwl/nx-set-shas@v4
